# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

variables:
  brunoCollectionPath: 'bruno/test1' # Update this path
  testReportFile: 'junit-report.xml'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    sudo npm install -g @usebruno/cli
  displayName: 'Install Bruno CLI'
  
- script: |
    bru run "bruno/test1" --output "junit-report.xml" --format junit --env local
  displayName: 'Run Bruno Tests and Generate JUnit Report'
  
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(testReportFile)'
    testRunTitle: 'Bruno API Tests'
  displayName: 'Publish Test Results to Azure DevOps'
